Adding -top to run script to define top module

diff --git a/run_iverilog_gtkwave b/run_iverilog_gtkwave
--- a/run_iverilog_gtkwave
+++ b/run_iverilog_gtkwave
@@ -5,7 +5,7 @@ all_project_files="ALU/alu.v Control/control.v \
                    InstrMem/instruction_memory.v RegisterBank/register_bank.v \
                    rv16r.v sim.v"
 all_v_files=$(find ~/git/RISCV16 -name "*.v")
-for f in $all_project_files; 
+for f in $all_project_files;
 do
     if ! echo $all_v_files |  grep -q "$f";
     then
@@ -14,7 +14,7 @@ do
     fi
 done
 
-PROGRAM_ARG_INTERFACE="-GUI -h"
+PROGRAM_ARG_INTERFACE="-GUI -h -top"
 
 print_usage () {
     echo "RISCV16 simulation scrtip."
@@ -23,42 +23,45 @@ print_usage () {
     do
         case $arg in
             "-GUI") echo "    -GUI: Execute with graphic interface.";;
-            "-h") echo   "    -h:   Show this usage.";;
+            "-h"  ) echo "    -h:   Show this usage.";;
+            "-top") echo "    -top <top-module>: Simulation's top module";;
         esac
     done
 }
 
+SKIP=0
+
 for arg in $@;
 do
-    # Checking if switch is implemented
-    HAS_SWITCH=0
-    for implemented_arg in $PROGRAM_ARG_INTERFACE;
-    do
-        if [ "$arg" == "$implemented_arg" ];
-        then
-            HAS_SWITCH=1
-        fi
-    done
-    if [ $HAS_SWITCH -eq 0 ];
+    if [ $SKIP -ne 1 ];
     then
-        echo "Unknown switch $arg"
-        print_usage
-        exit 1
+        # Processing switches
+        case $arg in
+            "-GUI") echo "Executing GUI mode."; GUI=1;;
+            "-top") TOP_MODULE=$(echo "$@" | grep -o -P "\-top\s+[^\s]+" | sed "s@\-top *@@"); SKIP=1;;
+            "-h"  ) print_usage; exit 0;;
+            *     ) echo "Unkown switch $arg"; print_usage; exit 1;;
+        esac
+    else
+        SKIP=0
     fi
-
-    # Processing switches
-    case $arg in
-        "-GUI") echo "Executing GUI mode."; GUI=1;;
-        "-h") print_usage; exit 0;;
-    esac
 done
+if [ -z $TOP_MODULE ];
+then
+    TOP_MODULE="sim"
+fi
+if ! grep -q -r -P "module\s+$TOP_MODULE" $all_v_files;
+then
+    echo "ERROR: Could not find top module \"$TOP_MODULE\""
+    exit 1
+fi
 
 IVLOG_VER=$(iverilog -V | sed -n '1p' | sed -r 's@^.*version ([0-9\.\-]+) .*$@\1@')
 if ! [ -z $(echo "$IVLOG_VER <= 10.1" | bc -l) ];
 then
-    iverilog $all_v_files -Wall -s sim 2>&1 | grep -v ".*Port declaration of.*"
+    iverilog $all_v_files -Wall -s "$TOP_MODULE" 2>&1 | grep -v ".*Port declaration of.*"
 else
-    iverilog $all_v_files -Wall -s sim
+    iverilog $all_v_files -Wall -s "$TOP_MODULE"
 fi
 
 vvp a.out
